version: '3.9'
services:
  bot:
    container_name: telegram-bot
    build: ./bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_URL=http://192.168.0.198:8080/api
    depends_on:
      - api-server

  api-server:
    container_name: api-server
    build: ./api
    environment:
      - PORT=8080
    ports:
      - "8080:8080"